server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

spring:
  application:
    name: smart-grading-backend
  logging:
    level:
      com.example.smartgrading.service: DEBUG

ai:
  llm:
    api-key: "ark-4ef84834-d169-4130-b86f-cc45e081061e-0b95f"
    model: "doubao-seed-evolving"
    endpoint: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
    # 备用配置
    # api-key: "sk-40358142538b45c781708e76986fa19e"
    # model: "qwen-plus"
    # endpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
#  ocr:
#    app-id: "123867472"
#    api-key: "xTLo2YY0GYmwCijmxAuhfyDe"
#    secret-key: "FPqrVVVLuqwuakgmXYIduIpM9a75nb9g"
  volcano:
    api-key: "ark-4ef84834-d169-4130-b86f-cc45e081061e-0b95f"
    model: "doubao-seed-2-1-pro-260628"
    endpoint: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"